# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: "linux"
    strategy:
      matrix:
        python2.7_gcc5_c++11:
          CXX: "g++-5"
          c++std: "11"
          packages: "gcc-5"
          python.version: "2.7"
        python3.5_gcc5_c++11:
          displayName: "linux Python3.5, gcc 5, c++11"
          CXX: "g++-5"
          c++std: "11"
          packages: "gcc-5"
          python.version: "3.5"
        python3.6_clang_c++14:
          CXX: "clang++"
          c++std: "14"
          packages: "clang"
          python.version: "3.6"
        python3.7_gcc7_c++17:
          CXX: "g++-7"
          c++std: "17"
          packages: "gcc-7"
          python.version: "3.7"

    pool:
      vmImage: "ubuntu-16.04"

    steps:
      - script: sudo -E apt-add-repository -y ppa:deadsnakes/ppa
        displayName: Update source
      - script: sudo apt update && sudo apt install -y libboost-all-dev python$(python.version)-dev $(packages)
        displayName: Install dependency
      - script: mkdir build
        displayName: Make build directory
      - task: CMake@1
        inputs:
          workingDirectory: 'build'
          cmakeArgs: >
            -DPYBIND11_PYTHON_VERSION=$(python.version) \
            -DCMAKE_CXX_STANDARD=11 \
            ..
        displayName: CMake
      - script: cd build && make -j`sysctl -n hw.ncpu`
        displayName: Build the project

    
  - job: "osx"
    strategy:
      matrix:
        python2.7_clang_c++11:
          CXX: "g++"
          c++std: "11"
          packages: ""
          python.version: "2.7"
        python3.7_gcc8_c++17:
          CXX: "g++"
          c++std: "17"
          packages: "python3"
          python.version: "3"
    pool:
      vmImage: 'macOS-10.13'

    steps:
      - script: brew update && brew install boost $(packages)
        displayName: Install dependency
      - script: mkdir build
        displayName: Make build directory
      - task: CMake@1
        inputs:
          workingDirectory: 'build'
          cmakeArgs: >
            -DPYBIND11_PYTHON_VERSION=$(python.version) \
            -DCMAKE_CXX_STANDARD=11 \
            ..
        displayName: CMake
      - script: cd build && make -j`sysctl -n hw.ncpu`
        displayName: Build the project